apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-app-deployment
  labels:
    app: survey-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
    spec:
#      imagePullSecrets:
#        - name: regcred
      containers:
        - name: survey-app
          image: saicherry93479/survey-app:${BUILD_NUMBER}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15